### ISSUE TITLE
Issue encountered while reproducing the code

### ISSUE THREAD

**Issue by Achestnut00** [Gandolfczjh/3D2Fool#10]
When I attempted to reproduce your code, I encountered the following error message:
Traceback (most recent call last):
  File "3D2Fool-main/3D2Fool-main/attack_base.py", line 224, in <module>
    attack(args)
  File "3D2Fool-main/3D2Fool-main/attack_base.py", line 180, in attack
    for i, (index, total_img, total_img0, mask, img) in enumerate(tqdm_loader):
ValueError: too many values to unpack (expected 5)
The dataset files are organized according to the requirements outlined in the README file. There are a total of 8400 images stored in the rgb folder. Could you please advise on how to resolve this issue?

**Comment by HPrivs** [comment]
I found the solution, comment out line 372 and uncomment line 373 in data_loader_mde.py

**Comment by Achestnut00** [comment]
Problem solved. Thank you.
