### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by Saahil18** [Gandolfczjh/3D2Fool#3]
Is the dataset which has all the camouflaged images created by you through Carla available?

**Comment by Gandolfczjh** [comment]
The training dataset is currently being uploaded and will be available soon!

**Comment by Saahil18** [comment]
> The training dataset is currently being uploaded and will be available soon!

Thanks for the reply, really appreciate it. I am looking forward to getting the dataset soon. Please let me know by when can I be expecting it.  to be available.
Thanks

**Comment by Gandolfczjh** [comment]
> > The training dataset is currently being uploaded and will be available soon!
> 
> Thanks for the reply, really appreciate it. I am looking forward to getting the dataset soon. Please let me know by when can I be expecting it. to be available. Thanks

In two days!😊

**Comment by Saahil18** [comment]
> > > The training dataset is currently being uploaded and will be available soon!
> > 
> > 
> > Thanks for the reply, really appreciate it. I am looking forward to getting the dataset soon. Please let me know by when can I be expecting it. to be available. Thanks
> 
> In two days!😊

Looking forward...
