### ISSUE TITLE
Unable to access dataset.

### ISSUE THREAD

**Issue by Saahil18** [Gandolfczjh/3D2Fool#4]
I truly appreciate you taking the time to upload the dataset. However, I'm unable to access Baidu Netdisk from outside China as it requires a Chinese number to log in. If it's not too much trouble, could you please upload the dataset to a more accessible platform or 
if at all possible can you send it to me directly?  
Thank you so much for your understanding and assistance.

**Comment by openparentheses** [comment]
Can you upload the dataset to Google Drive/OneDrive/Dropbox/MEGA and share the link? Unfortunately I can't access the dataset to run the code either. Thank you.
