### ISSUE TITLE
the environment are faile to install

### ISSUE THREAD

**Issue by Daliuq** [Gandolfczjh/3D2Fool#8]
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (neural_renderer_pytorch)

**Comment by Gandolfczjh** [comment]
I hope these links can address your concerns.
[blog1](https://stackoverflow.com/questions/66613139/failed-to-install-neural-render-pytorch), [blog2](https://stackoverflow.com/questions/65173409/building-wheel-for-neural-renderer-pytorch-setup-py-installing-multiperson), [issues](https://github.com/iPERDance/iPERCore/issues/12)
